// Stores Priceo backend endpoint paths in one place.
export const priceoEndpoints = {
  PRODUCTS: "/product",
  PRODUCT_BY_ID: (id) => `/product/${id}`,
  CART: "/cart",
  APPLY_COUPON: "/cart/applyCoupon",
  WISHLIST: "/wishlist",
  NOTIFICATIONS: "/notification",
  ADMIN_NOTIFICATIONS: "/admin/notification",
  ORDERS: "/order",
  USER_ORDERS: "/order/user",
  ORDER_BY_ID: (id) => `/order/${id}`,
  ADMIN_ORDER_STATS: "/admin/ordersStats",
  ADMIN_SALES_STATS: "/admin/statistics",
  COMPLAINTS: "/complaint",
  COUPONS: "/coupon",
  COUPON_BY_ID: (id) => `/coupon/${id}`,
  MY_REPORTS: "/report/myreport",
  REPORT_BY_ID: (id) => `/report/${id}`,
};
